model:
  input_channels: 3
  hidden_channels: 32
  num_layers: 5
  num_classes: 1
  lr: 5e-3
data:
  dataset_path: '/mnt/ceph/users/polymathic/mmoma/datasets/crossmatched_dset/sdss16b_decals16'
  batch_size: 512
  num_workers: 0
  split: 'random'
  val_size: 0.2
  range_compression_factor: 0.01
trainer:
  max_epochs: 30
  accelerator: gpu
  limit_train_batches: 100
  limit_val_batches: 10
  callbacks:
  - class_path: utils.R2ScoreCallback
