model:
  class_path: model.PhotometryMLP
  init_args:
    n_out: 5
    lr: 5e-4
data:
  class_path: dataset.PROVABGSDataset
  init_args:
    dataset_path: '/mnt/home/lparker/ceph/decals_provabgs'
    modality: 'photometry'
    batch_size: 128
    num_workers: 16
    val_size: 0.2
trainer:
  max_epochs: 30
  accelerator: gpu
  limit_train_batches: 100
  limit_val_batches: 20
  callbacks:
  - class_path: utils.R2ScoreCallback
