model:
  class_path: model.PhotometryMLP
  init_args:
    input_channels: 3 # G, R, Z
    num_layers: 5
    hidden_channels: 512
    n_out: 5
    lr: 5e-4
data:
  class_path: dataset.PROVABGSDataset
  init_args:
    dataset_path: '/mnt/ceph/users/polymathic/AstroPile_v1/desi_provabgs/'
    modality: 'photometry'
    batch_size: 256
    val_size: 0.2
trainer:
  max_epochs: 30
  accelerator: gpu
  callbacks:
  - class_path: utils.R2ScoreCallback
