model:
  class_path: model.SpectrumConvAtt
  init_args:
    n_out: 5
    lr: 5e-4
    filters:
    - 8
    - 16
    - 32
    - 64
data:
  class_path: dataset.PROVABGSDataset
  init_args:
    dataset_path: '/mnt/home/lparker/ceph/desi_provabgs'
    modality: 'spectrum'
    batch_size: 128
    val_size: 0.2
trainer:
  max_epochs: 100
  accelerator: gpu
  callbacks:
  - class_path: utils.R2ScoreCallback
