model:
  class_path: model.ResNet18_spectrum
  init_args:
    n_out: 5
data:
  class_path: dataset.SpectrumDataset
  init_args:
    dataset_path: '/scratch/msmith/projects/astropile_project/astropile/provabgs/provabgs.py'
    cache_path: '/scratch/msmith/projects/astropile_project/astropile_compiled/provabgs'
    num_workers: 16
    modality: 'provabgs'
    batch_size: 128
    val_size: 0.20
trainer:
  max_epochs: 30 
  accelerator: gpu
  callbacks:
    - class_path: utils.R2ScoreCallback
