# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing tiny datasets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r dset-requirements.txt
    - name: Find all the scripts subfolders and execute the testing script
      run: |
        export SSP_PDR_USR = ${{ secrets.SSP_PDR_USR }}
        export SSP_PDR_PWD = ${{ secrets.SSP_PDR_PWD }}
        cd scripts
        for folder in */; do
          echo "Entering $folder" # Print that we are entering this particular folder
          cd "$folder"
          
          if [ -f "test.sh" ]; then
            bash test.sh
          fi
          cd ..
        done
        cd scripts/hsc && bash test.sh
